{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "48e47361",
   "metadata": {},
   "outputs": [],
   "source": [
    "1. Create a DB with doctor and doctor ID & patients visited\n",
    "In [1]:\n",
    "import mysql.connector\n",
    "In [2]:\n",
    "mydb = mysql.connector.connect(\n",
    "  host=\"localhost\",\n",
    "  user=\"root\",\n",
    "  password=\"1234\"\n",
    ")\n",
    "In [3]:\n",
    "print(mydb)\n",
    "<mysql.connector.connection_cext.CMySQLConnection object at 0x0000021634F8A790>\n",
    "In [8]:\n",
    "dbse = mydb.cursor()\n",
    "\n",
    "dbse.execute(\"CREATE DATABASE Doctors1\")\n",
    "In [9]:\n",
    "dbse = mydb.cursor()\n",
    "\n",
    "dbse.execute(\"SHOW DATABASES\")\n",
    "\n",
    "for entry in dbse:\n",
    "  print(entry)\n",
    "('doctor',)\n",
    "('doctors1',)\n",
    "('information_schema',)\n",
    "('mydatabase',)\n",
    "('mysql',)\n",
    "('performance_schema',)\n",
    "('sakila',)\n",
    "('sys',)\n",
    "('world',)\n",
    "In [10]:\n",
    "mydb = mysql.connector.connect(\n",
    "  host=\"localhost\",\n",
    " user=\"root\",\n",
    "  password=\"1234\",\n",
    "  database=\"Doctors1\"\n",
    ")\n",
    "dbse = mydb.cursor()\n",
    "\n",
    "dbse.execute(\"CREATE TABLE Doctors (dr_id VARCHAR(255), Patient_visited VARCHAR(255))\")\n",
    "In [11]:\n",
    "dbse = mydb.cursor()\n",
    "\n",
    "dbse.execute(\"SHOW TABLES\")\n",
    "\n",
    "for value in dbse:\n",
    "  print(value)\n",
    "('doctors',)\n",
    "In [12]:\n",
    "dbse = mydb.cursor()\n",
    "\n",
    "sql = \"INSERT INTO Doctors (dr_id , Patient_visited) VALUES (%s,%s)\"\n",
    "val = [\n",
    "  ('DID1','10'),\n",
    "    ('DID2','3'),\n",
    "    ('DID3','8'),\n",
    "    ('DID5','0'),\n",
    "    ('DID123','15'),\n",
    "    ('DID26','9'),\n",
    "    ('DID78','0'),\n",
    "    ('DID65','0'),\n",
    "     ('DID23','15'),\n",
    "    ('DID262','9'),\n",
    "    ('DID783','0'),\n",
    "    ('DID651','0'), \n",
    "    ('DID13','19'),\n",
    "    ('DID267','7'),\n",
    "    ('DID8','0'),\n",
    "    ('DID59','0')    \n",
    "]\n",
    "dbse.executemany(sql, val)\n",
    "\n",
    "mydb.commit()\n",
    "\n",
    "print(dbse.rowcount, \"was inserted.\")\n",
    "16 was inserted.\n",
    "2. Get the doctor(s) who have more than 5 patients visited\n",
    "In [15]:\n",
    "mycursor = mydb.cursor()\n",
    "\n",
    "mycursor.execute(\"SELECT * FROM Doctors where Patient_visited >5\")\n",
    "\n",
    "myresult = mycursor.fetchall()\n",
    "\n",
    "for x in myresult:\n",
    "  print(x)\n",
    "('DID1', '10')\n",
    "('DID3', '8')\n",
    "('DID123', '15')\n",
    "('DID26', '9')\n",
    "('DID23', '15')\n",
    "('DID262', '9')\n",
    "('DID13', '19')\n",
    "('DID267', '7')\n",
    "3. Get the doctors with no patients visit\n",
    "In [14]:\n",
    "mycursor = mydb.cursor()\n",
    "\n",
    "mycursor.execute(\"SELECT * FROM Doctors where Patient_visited=0\")\n",
    "\n",
    "myresult = mycursor.fetchall()\n",
    "\n",
    "for x in myresult:\n",
    "  print(x)\n",
    "('DID5', '0')\n",
    "('DID78', '0')\n",
    "('DID65', '0')\n",
    "('DID783', '0')\n",
    "('DID651', '0')\n",
    "('DID8', '0')\n",
    "('DID59', '0')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
