{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "60ab0ba5",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "• Create a connection for DB and print the version using a python program\n",
    "In [1]:\n",
    "import mysql.connector\n",
    "In [2]:\n",
    "mydb = mysql.connector.connect(\n",
    "  host=\"localhost\",\n",
    "  user=\"root\",\n",
    "  password=\"1234\"\n",
    ")\n",
    "In [3]:\n",
    "print(mydb)\n",
    "<mysql.connector.connection_cext.CMySQLConnection object at 0x0000016A60164700>\n",
    "In [4]:\n",
    "import sys\n",
    "cur = mydb.cursor()\n",
    "cur.execute(\"SELECT VERSION()\")\n",
    "data = cur.fetchone()\n",
    "print(\"DBMS Version :\",str(data))\n",
    "DBMS Version : ('8.0.25',)\n",
    "• Create a multiple tables & insert data in table\n",
    "In [7]:\n",
    "dbse = mydb.cursor()\n",
    "\n",
    "dbse.execute(\"CREATE DATABASE mydatabase\")\n",
    "In [8]:\n",
    "dbse = mydb.cursor()\n",
    "\n",
    "dbse.execute(\"SHOW DATABASES\")\n",
    "\n",
    "for entry in dbse:\n",
    "  print(entry)\n",
    "('information_schema',)\n",
    "('mydatabase',)\n",
    "('mysql',)\n",
    "('performance_schema',)\n",
    "('sakila',)\n",
    "('sys',)\n",
    "('world',)\n",
    "In [10]:\n",
    "mydb = mysql.connector.connect(\n",
    "  host=\"localhost\",\n",
    " user=\"root\",\n",
    "  password=\"1234\",\n",
    "  database=\"mydatabase\"\n",
    ")\n",
    "dbse = mydb.cursor()\n",
    "\n",
    "dbse.execute(\"CREATE TABLE customers (Employee_name VARCHAR(255), Employee_dep VARCHAR(255), Employee_id VARCHAR(255))\")\n",
    "In [11]:\n",
    "dbse = mydb.cursor()\n",
    "dbse.execute(\"SHOW TABLES\")\n",
    "\n",
    "for value in dbse:\n",
    "  print(value)\n",
    "('customers',)\n",
    "In [14]:\n",
    "dbse = mydb.cursor()\n",
    "\n",
    "dbse.execute(\"CREATE TABLE Office (emp_name VARCHAR(255), Employee_id VARCHAR(255) ,EMP_ADDRESS VARCHAR(255))\")\n",
    "In [15]:\n",
    "dbse =mydb.cursor()\n",
    "dbse.execute(\"CREATE TABLE Student(rollno INT(24) , STUD_NAME VARCHAR(255) , MARK INT(3))\")\n",
    "In [16]:\n",
    "dbse = mydb.cursor()\n",
    "\n",
    "dbse.execute(\"SHOW TABLES\")\n",
    "\n",
    "for value in dbse:\n",
    "  print(value)\n",
    "('customers',)\n",
    "('office',)\n",
    "('student',)\n",
    "• Create a employee table and read all the employee name in the table using for loop\n",
    "In [24]:\n",
    "mydb = mysql.connector.connect(\n",
    "  host=\"localhost\",\n",
    " user=\"root\",\n",
    "  password=\"1234\",\n",
    "  database=\"mydatabase\"\n",
    ")\n",
    "\n",
    "mycursor = mydb.cursor()\n",
    "\n",
    "mycursor.execute(\"CREATE TABLE Employee1 (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), address VARCHAR(255))\")\n",
    "In [30]:\n",
    "mydb = mysql.connector.connect(\n",
    "  host=\"localhost\",\n",
    "  user=\"root\",\n",
    "  password=\"1234\",\n",
    "  database=\"mydatabase\"\n",
    ")\n",
    "mycursor = mydb.cursor()\n",
    "\n",
    "sql = \"INSERT INTO Employee1 (id, name, address) VALUES (%s, %s,%s)\"\n",
    "val = (\"123\",\"divya\",\"T Nagar 56\")\n",
    "mycursor.execute(sql, val)\n",
    "\n",
    "mydb.commit()\n",
    "\n",
    "print(mycursor.rowcount, \"record inserted.\")\n",
    "1 record inserted.\n",
    "In [31]:\n",
    "mycursor = mydb.cursor()\n",
    "\n",
    "sql = \"INSERT INTO Employee1 (id, name, address) VALUES (%s, %s,%s)\"\n",
    "val = (\"124\",\"Renu\",\"T Nagar 58\")\n",
    "mycursor.execute(sql, val)\n",
    "\n",
    "mydb.commit()\n",
    "\n",
    "print(mycursor.rowcount, \"record inserted.\")\n",
    "1 record inserted.\n",
    "In [32]:\n",
    "mycursor = mydb.cursor()\n",
    "\n",
    "sql = \"INSERT INTO Employee1 (id, name, address) VALUES (%s, %s,%s)\"\n",
    "val = (\"125\",\"Janani\",\"Kamarajar Salai 58\")\n",
    "mycursor.execute(sql, val)\n",
    "\n",
    "mydb.commit()\n",
    "\n",
    "print(mycursor.rowcount, \"record inserted.\")\n",
    "1 record inserted.In [41]:\n",
    "mycursor = mydb.cursor()\n",
    "\n",
    "sql = \"INSERT INTO Employee1 (id,name, address) VALUES (%s,%s,%s)\"\n",
    "val = [\n",
    "  ('1','Peter', 'Lowstreet 4'),\n",
    "  ('2','Amy', 'Apple st 652'),\n",
    "  ('3','Hannah', 'Mountain 21'),\n",
    "  ('4','Michael', 'Valley 345'),\n",
    "  ('5','Sandy', 'Ocean blvd 2'),\n",
    "  ('6','Viola', 'Sideway 1633')\n",
    "]\n",
    "\n",
    "mycursor.executemany(sql, val)\n",
    "\n",
    "mydb.commit()\n",
    "\n",
    "print(mycursor.rowcount, \"was inserted.\")\n",
    "6 was inserted.\n",
    "In [42]:\n",
    "mycursor = mydb.cursor()\n",
    "\n",
    "mycursor.execute(\"SELECT * FROM Employee1\")\n",
    "\n",
    "myresult = mycursor.fetchall()\n",
    "\n",
    "for x in myresult:\n",
    "  print(x)\n",
    "(1, 'Peter', 'Lowstreet 4')\n",
    "(2, 'Amy', 'Apple st 652')\n",
    "(3, 'Hannah', 'Mountain 21')\n",
    "(4, 'Michael', 'Valley 345')\n",
    "(5, 'Sandy', 'Ocean blvd 2')\n",
    "(6, 'Viola', 'Sideway 1633')\n",
    "(123, 'divya', 'T Nagar 56')\n",
    "(124, 'Renu', 'T Nagar 58')\n",
    "(125, 'Janani', 'Kamarajar Salai 58')\n",
    "In [43]:\n",
    "mycursor = mydb.cursor()\n",
    "\n",
    "mycursor.execute(\"SELECT name FROM Employee1\")\n",
    "\n",
    "myresult = mycursor.fetchall()\n",
    "\n",
    "for x in myresult:\n",
    "  print(x)\n",
    "('Peter',)\n",
    "('Amy',)\n",
    "('Hannah',)\n",
    "('Michael',)\n",
    "('Sandy',)\n",
    "('Viola',)\n",
    "('divya',)\n",
    "('Renu',)\n",
    "('Janani',)\n",
    "In [ ]:\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
